name: Build and Save Python Wheel

on:
  push:
    branches:
      - '**'    # Trigger on any branch push
  pull_request:
    branches:
      - '**'    # Trigger on any branch pull request

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository on the current branch
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures that the full history is cloned to handle any branch-specific build needs
      
      - name: Create Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag -a v1.0.${{ github.run_number }} -m "Release version v1.0.${{ github.run_number }}"
          git push origin v1.0.${{ github.run_number }}

      # Setup Python and install setuptools
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel

      # Run the build script and capture the output directory
      - name: Run build script
        id: build
        run: |
          bazel build ...

      - name: Run Bazel Tests
        run: |
          bazel test ...
                
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: bazel-bin/*.whl

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: bazel-bin/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}